// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages2.proto

#ifndef PROTOBUF_INCLUDED_messages2_2eproto
#define PROTOBUF_INCLUDED_messages2_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_messages2_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_messages2_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_messages2_2eproto();
class UpdateSignal;
class UpdateSignalDefaultTypeInternal;
extern UpdateSignalDefaultTypeInternal _UpdateSignal_default_instance_;
class UpdateSignal_StaResult;
class UpdateSignal_StaResultDefaultTypeInternal;
extern UpdateSignal_StaResultDefaultTypeInternal _UpdateSignal_StaResult_default_instance_;
class UpdateSignal_StaResult_LinkMeasurement;
class UpdateSignal_StaResult_LinkMeasurementDefaultTypeInternal;
extern UpdateSignal_StaResult_LinkMeasurementDefaultTypeInternal _UpdateSignal_StaResult_LinkMeasurement_default_instance_;
namespace google {
namespace protobuf {
template<> ::UpdateSignal* Arena::CreateMaybeMessage<::UpdateSignal>(Arena*);
template<> ::UpdateSignal_StaResult* Arena::CreateMaybeMessage<::UpdateSignal_StaResult>(Arena*);
template<> ::UpdateSignal_StaResult_LinkMeasurement* Arena::CreateMaybeMessage<::UpdateSignal_StaResult_LinkMeasurement>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class UpdateSignal_StaResult_LinkMeasurement : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UpdateSignal.StaResult.LinkMeasurement) */ {
 public:
  UpdateSignal_StaResult_LinkMeasurement();
  virtual ~UpdateSignal_StaResult_LinkMeasurement();

  UpdateSignal_StaResult_LinkMeasurement(const UpdateSignal_StaResult_LinkMeasurement& from);

  inline UpdateSignal_StaResult_LinkMeasurement& operator=(const UpdateSignal_StaResult_LinkMeasurement& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UpdateSignal_StaResult_LinkMeasurement(UpdateSignal_StaResult_LinkMeasurement&& from) noexcept
    : UpdateSignal_StaResult_LinkMeasurement() {
    *this = ::std::move(from);
  }

  inline UpdateSignal_StaResult_LinkMeasurement& operator=(UpdateSignal_StaResult_LinkMeasurement&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const UpdateSignal_StaResult_LinkMeasurement& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdateSignal_StaResult_LinkMeasurement* internal_default_instance() {
    return reinterpret_cast<const UpdateSignal_StaResult_LinkMeasurement*>(
               &_UpdateSignal_StaResult_LinkMeasurement_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(UpdateSignal_StaResult_LinkMeasurement* other);
  friend void swap(UpdateSignal_StaResult_LinkMeasurement& a, UpdateSignal_StaResult_LinkMeasurement& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UpdateSignal_StaResult_LinkMeasurement* New() const final {
    return CreateMaybeMessage<UpdateSignal_StaResult_LinkMeasurement>(NULL);
  }

  UpdateSignal_StaResult_LinkMeasurement* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<UpdateSignal_StaResult_LinkMeasurement>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const UpdateSignal_StaResult_LinkMeasurement& from);
  void MergeFrom(const UpdateSignal_StaResult_LinkMeasurement& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpdateSignal_StaResult_LinkMeasurement* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // fixed64 BSSID = 1;
  void clear_bssid();
  static const int kBSSIDFieldNumber = 1;
  ::google::protobuf::uint64 bssid() const;
  void set_bssid(::google::protobuf::uint64 value);

  // sint32 rssi = 2;
  void clear_rssi();
  static const int kRssiFieldNumber = 2;
  ::google::protobuf::int32 rssi() const;
  void set_rssi(::google::protobuf::int32 value);

  // sint32 snr = 3;
  void clear_snr();
  static const int kSnrFieldNumber = 3;
  ::google::protobuf::int32 snr() const;
  void set_snr(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UpdateSignal.StaResult.LinkMeasurement)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 bssid_;
  ::google::protobuf::int32 rssi_;
  ::google::protobuf::int32 snr_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_messages2_2eproto;
};
// -------------------------------------------------------------------

class UpdateSignal_StaResult : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UpdateSignal.StaResult) */ {
 public:
  UpdateSignal_StaResult();
  virtual ~UpdateSignal_StaResult();

  UpdateSignal_StaResult(const UpdateSignal_StaResult& from);

  inline UpdateSignal_StaResult& operator=(const UpdateSignal_StaResult& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UpdateSignal_StaResult(UpdateSignal_StaResult&& from) noexcept
    : UpdateSignal_StaResult() {
    *this = ::std::move(from);
  }

  inline UpdateSignal_StaResult& operator=(UpdateSignal_StaResult&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const UpdateSignal_StaResult& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdateSignal_StaResult* internal_default_instance() {
    return reinterpret_cast<const UpdateSignal_StaResult*>(
               &_UpdateSignal_StaResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(UpdateSignal_StaResult* other);
  friend void swap(UpdateSignal_StaResult& a, UpdateSignal_StaResult& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UpdateSignal_StaResult* New() const final {
    return CreateMaybeMessage<UpdateSignal_StaResult>(NULL);
  }

  UpdateSignal_StaResult* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<UpdateSignal_StaResult>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const UpdateSignal_StaResult& from);
  void MergeFrom(const UpdateSignal_StaResult& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpdateSignal_StaResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef UpdateSignal_StaResult_LinkMeasurement LinkMeasurement;

  // accessors -------------------------------------------------------

  // repeated .UpdateSignal.StaResult.LinkMeasurement linkmeasurements = 2;
  int linkmeasurements_size() const;
  void clear_linkmeasurements();
  static const int kLinkmeasurementsFieldNumber = 2;
  ::UpdateSignal_StaResult_LinkMeasurement* mutable_linkmeasurements(int index);
  ::google::protobuf::RepeatedPtrField< ::UpdateSignal_StaResult_LinkMeasurement >*
      mutable_linkmeasurements();
  const ::UpdateSignal_StaResult_LinkMeasurement& linkmeasurements(int index) const;
  ::UpdateSignal_StaResult_LinkMeasurement* add_linkmeasurements();
  const ::google::protobuf::RepeatedPtrField< ::UpdateSignal_StaResult_LinkMeasurement >&
      linkmeasurements() const;

  // fixed64 StaMAC = 1;
  void clear_stamac();
  static const int kStaMACFieldNumber = 1;
  ::google::protobuf::uint64 stamac() const;
  void set_stamac(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:UpdateSignal.StaResult)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::UpdateSignal_StaResult_LinkMeasurement > linkmeasurements_;
  ::google::protobuf::uint64 stamac_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_messages2_2eproto;
};
// -------------------------------------------------------------------

class UpdateSignal : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UpdateSignal) */ {
 public:
  UpdateSignal();
  virtual ~UpdateSignal();

  UpdateSignal(const UpdateSignal& from);

  inline UpdateSignal& operator=(const UpdateSignal& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UpdateSignal(UpdateSignal&& from) noexcept
    : UpdateSignal() {
    *this = ::std::move(from);
  }

  inline UpdateSignal& operator=(UpdateSignal&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const UpdateSignal& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdateSignal* internal_default_instance() {
    return reinterpret_cast<const UpdateSignal*>(
               &_UpdateSignal_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(UpdateSignal* other);
  friend void swap(UpdateSignal& a, UpdateSignal& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UpdateSignal* New() const final {
    return CreateMaybeMessage<UpdateSignal>(NULL);
  }

  UpdateSignal* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<UpdateSignal>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const UpdateSignal& from);
  void MergeFrom(const UpdateSignal& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpdateSignal* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef UpdateSignal_StaResult StaResult;

  // accessors -------------------------------------------------------

  // repeated .UpdateSignal.StaResult staresults = 2;
  int staresults_size() const;
  void clear_staresults();
  static const int kStaresultsFieldNumber = 2;
  ::UpdateSignal_StaResult* mutable_staresults(int index);
  ::google::protobuf::RepeatedPtrField< ::UpdateSignal_StaResult >*
      mutable_staresults();
  const ::UpdateSignal_StaResult& staresults(int index) const;
  ::UpdateSignal_StaResult* add_staresults();
  const ::google::protobuf::RepeatedPtrField< ::UpdateSignal_StaResult >&
      staresults() const;

  // fixed64 BSSID = 1;
  void clear_bssid();
  static const int kBSSIDFieldNumber = 1;
  ::google::protobuf::uint64 bssid() const;
  void set_bssid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:UpdateSignal)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::UpdateSignal_StaResult > staresults_;
  ::google::protobuf::uint64 bssid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_messages2_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UpdateSignal_StaResult_LinkMeasurement

// fixed64 BSSID = 1;
inline void UpdateSignal_StaResult_LinkMeasurement::clear_bssid() {
  bssid_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UpdateSignal_StaResult_LinkMeasurement::bssid() const {
  // @@protoc_insertion_point(field_get:UpdateSignal.StaResult.LinkMeasurement.BSSID)
  return bssid_;
}
inline void UpdateSignal_StaResult_LinkMeasurement::set_bssid(::google::protobuf::uint64 value) {
  
  bssid_ = value;
  // @@protoc_insertion_point(field_set:UpdateSignal.StaResult.LinkMeasurement.BSSID)
}

// sint32 rssi = 2;
inline void UpdateSignal_StaResult_LinkMeasurement::clear_rssi() {
  rssi_ = 0;
}
inline ::google::protobuf::int32 UpdateSignal_StaResult_LinkMeasurement::rssi() const {
  // @@protoc_insertion_point(field_get:UpdateSignal.StaResult.LinkMeasurement.rssi)
  return rssi_;
}
inline void UpdateSignal_StaResult_LinkMeasurement::set_rssi(::google::protobuf::int32 value) {
  
  rssi_ = value;
  // @@protoc_insertion_point(field_set:UpdateSignal.StaResult.LinkMeasurement.rssi)
}

// sint32 snr = 3;
inline void UpdateSignal_StaResult_LinkMeasurement::clear_snr() {
  snr_ = 0;
}
inline ::google::protobuf::int32 UpdateSignal_StaResult_LinkMeasurement::snr() const {
  // @@protoc_insertion_point(field_get:UpdateSignal.StaResult.LinkMeasurement.snr)
  return snr_;
}
inline void UpdateSignal_StaResult_LinkMeasurement::set_snr(::google::protobuf::int32 value) {
  
  snr_ = value;
  // @@protoc_insertion_point(field_set:UpdateSignal.StaResult.LinkMeasurement.snr)
}

// -------------------------------------------------------------------

// UpdateSignal_StaResult

// fixed64 StaMAC = 1;
inline void UpdateSignal_StaResult::clear_stamac() {
  stamac_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UpdateSignal_StaResult::stamac() const {
  // @@protoc_insertion_point(field_get:UpdateSignal.StaResult.StaMAC)
  return stamac_;
}
inline void UpdateSignal_StaResult::set_stamac(::google::protobuf::uint64 value) {
  
  stamac_ = value;
  // @@protoc_insertion_point(field_set:UpdateSignal.StaResult.StaMAC)
}

// repeated .UpdateSignal.StaResult.LinkMeasurement linkmeasurements = 2;
inline int UpdateSignal_StaResult::linkmeasurements_size() const {
  return linkmeasurements_.size();
}
inline void UpdateSignal_StaResult::clear_linkmeasurements() {
  linkmeasurements_.Clear();
}
inline ::UpdateSignal_StaResult_LinkMeasurement* UpdateSignal_StaResult::mutable_linkmeasurements(int index) {
  // @@protoc_insertion_point(field_mutable:UpdateSignal.StaResult.linkmeasurements)
  return linkmeasurements_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UpdateSignal_StaResult_LinkMeasurement >*
UpdateSignal_StaResult::mutable_linkmeasurements() {
  // @@protoc_insertion_point(field_mutable_list:UpdateSignal.StaResult.linkmeasurements)
  return &linkmeasurements_;
}
inline const ::UpdateSignal_StaResult_LinkMeasurement& UpdateSignal_StaResult::linkmeasurements(int index) const {
  // @@protoc_insertion_point(field_get:UpdateSignal.StaResult.linkmeasurements)
  return linkmeasurements_.Get(index);
}
inline ::UpdateSignal_StaResult_LinkMeasurement* UpdateSignal_StaResult::add_linkmeasurements() {
  // @@protoc_insertion_point(field_add:UpdateSignal.StaResult.linkmeasurements)
  return linkmeasurements_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UpdateSignal_StaResult_LinkMeasurement >&
UpdateSignal_StaResult::linkmeasurements() const {
  // @@protoc_insertion_point(field_list:UpdateSignal.StaResult.linkmeasurements)
  return linkmeasurements_;
}

// -------------------------------------------------------------------

// UpdateSignal

// fixed64 BSSID = 1;
inline void UpdateSignal::clear_bssid() {
  bssid_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UpdateSignal::bssid() const {
  // @@protoc_insertion_point(field_get:UpdateSignal.BSSID)
  return bssid_;
}
inline void UpdateSignal::set_bssid(::google::protobuf::uint64 value) {
  
  bssid_ = value;
  // @@protoc_insertion_point(field_set:UpdateSignal.BSSID)
}

// repeated .UpdateSignal.StaResult staresults = 2;
inline int UpdateSignal::staresults_size() const {
  return staresults_.size();
}
inline void UpdateSignal::clear_staresults() {
  staresults_.Clear();
}
inline ::UpdateSignal_StaResult* UpdateSignal::mutable_staresults(int index) {
  // @@protoc_insertion_point(field_mutable:UpdateSignal.staresults)
  return staresults_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UpdateSignal_StaResult >*
UpdateSignal::mutable_staresults() {
  // @@protoc_insertion_point(field_mutable_list:UpdateSignal.staresults)
  return &staresults_;
}
inline const ::UpdateSignal_StaResult& UpdateSignal::staresults(int index) const {
  // @@protoc_insertion_point(field_get:UpdateSignal.staresults)
  return staresults_.Get(index);
}
inline ::UpdateSignal_StaResult* UpdateSignal::add_staresults() {
  // @@protoc_insertion_point(field_add:UpdateSignal.staresults)
  return staresults_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UpdateSignal_StaResult >&
UpdateSignal::staresults() const {
  // @@protoc_insertion_point(field_list:UpdateSignal.staresults)
  return staresults_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_messages2_2eproto
